name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write # OIDC 核心就是靠它

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org' # 设置官方源

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Library
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v6
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v6
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v6

      - run: npm ci
      - run: npm publish